/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const T>(t: T): T
  const __VLS_directiveBindingRestFields: { instance: null
  const __VLS_intrinsics: import('vue/jsx-runtime').JSX.IntrinsicElements
  const __VLS_placeholder: any
  const __VLS_unref: typeof import('vue').unref
}
