name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 下载代码仓库
      - uses: actions/checkout@v2

      # 设置 Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 登录 Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 安装依赖并构建
      - name: Install and Build
        run: |
          npm install -g pnpm && \
          pnpm install --no-frozen-lockfile && \
          pnpm build

      # 构建并推送 Docker 镜像
      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/vue-admin:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/vue-admin:latest

      # SSH 连接并部署
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHPWD }}
          port: 22
          script: |
            # 拉取最新镜像
            docker pull ${{ secrets.DOCKER_USERNAME }}/vue-admin:latest

            # 确保网络存在
            docker network create app_common-network 2>/dev/null || true

            # 停止并删除旧容器
            docker stop vue-admin-app || true
            docker rm vue-admin-app || true

            # 运行新容器
            docker run -d --name vue-admin-app \
              -p 8080:8080 \
              --network=app_common-network \
              ${{ secrets.DOCKER_USERNAME }}/vue-admin:latest
